name: Instance image updater

# Ref: schedule - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
# on:
#   schedule:
#     - cron: '0 5 * * *' # At 5:00

# Currently, use issee_comment event for testing
on:
  issues:
    types: [opened]

jobs:
  update-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write 
#       pull-requests: write

    steps:
    - name: Create a dummy
      id: checker
      shell: bash
      run: |
        cat > output.md <<EOF
        ### header
        - bullet
        text
        EOF
        echo ::set-output name=output_path::"./output.md"
        
      
    - name: Create Issue From File
    
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: An example issue
        content-filepath: ${{ steps.checker.outputs.output_path }}
        labels: |
          test
      
#     steps:
#     - name: Create commit comment
#       uses: peter-evans/create-or-update-comment@v2
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#         issue-number: ${{ github.event.issue.number }}
#         body: |
#           This is a multi-line test comment
#           - With GitHub **Markdown** :sparkles:
#           - Created by [create-or-update-comment][1]

#           [1]: https://github.com/peter-evans/create-or-update-comment
