name: Instance image updater

# Currently, use workflow_dispatch by which we can manually run this workflow
on:
  workflow_dispatch:

jobs:
  update-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write 
#       pull-requests: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: cloud-barista/cb-tumblebug
        ref: v0.6.3
        
    - name: Setup frameworks
      shell: bash
      run: |
      
        # Setup credentials
        cp ./conf/template.credentials.conf ./conf/credentials.conf
        
        # Append AWS cred
        sed -i "s,CredentialVal01\[\$IndexAWS\]=,&${{secrets.AWS_KEY}}," ./conf/credentials.conf
        sed -i "s,CredentialVal02\[\$IndexAWS\]=,&${{secrets.AWS_VALUE}}," ./conf/credentials.conf
        
        echo "(DEBUG) Print credential.conf (Secrets are masked as ***)"
        cat ./conf/credentials.conf
        
        source conf/setup.env        
        
        echo "CBTUMBLEBUG_ROOT:"
        echo $CBTUMBLEBUG_ROOT
        
        ls -al        
        
        # Run CB-Spider container
        echo "(DEBUG) Run CB-Spider container"
        CONTAINER_VOLUME_PATH="$CBTUMBLEBUG_ROOT/container-volume/cb-spider-container"
        CONTAINER_VOLUME_OPTION="-v $CONTAINER_VOLUME_PATH:/root/go/src/github.com/cloud-barista/cb-spider/meta_db"
        sudo docker run -d --rm -p 1024:1024 -p 2048:2048 \
               ${CONTAINER_VOLUME_OPTION} \
                \
               --name cb-spider \
               cloudbaristaorg/cb-spider:0.6.8
        
        sudo docker ps -a
        
        echo "Sleep 15 sec"
        sleep 15
        
        # Run CB-Tumblebug Server
        echo "(DEBUG) Run CB-Tumblebug server"
        cd src
        make        
        make run &
        
        echo "Sleep 10 sec"
        sleep 1
        
    - name: Do something
      shell: bash
      run: |
      
        echo "(DEBUG) Health-check, CB-Spider container"
        curl -sX GET http://localhost:1024/spider/cloudos |json_pp
        
        echo "(DEBUG) Health-check, CB-Tumblebug server"
        curl http://localhost:1323/tumblebug/health
                
        echo "(DEBUG) Create issue content"
        cat <<EOF > output.md
        ### header
        - bullet
        - bullet 
        1. number
        
        message start
        
        Hello world!!
        This issue is created by "peter-evans/create-issue-from-file@v4"

        message end
        EOF
      
    - name: Create an issue from file    
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: An example issue
        content-filepath: output.md
        labels: |
          test
          need update
          good first issue
