name: Instance image updater

# Currently, use workflow_dispatch by which we can manually run this workflow
on:
  workflow_dispatch:

jobs:
  update-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write 
#       pull-requests: write

    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: cloud-barista/cb-tumblebug
        ref: v0.6.3
        
    - name: Create a dummy
      id: checker
      shell: bash
      run: |
        ls -al        
        GIT_STATUS=$(git status)
        
        cat > output.md <<EOF
        ### header
        - bullet
        (start)
        
        ${GIT_STATUS}
        
        (end)
        EOF
        echo ::set-output name=output_path::"./output.md"
        
      
    - name: Create an issue from file    
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: An example issue
        content-filepath: output.md
        labels: |
          outdated
          lang/ko
