name: Instance image updater

# Ref: schedule - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
# on:
#   schedule:
#     - cron: '0 5 * * *' # At 5:00

# Currently, use issee_comment event for testing
on:
  issues:
    types: [opened]

jobs:
  update-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write
#       pull-requests: write
      
    steps:
    - name: Create commit comment
      uses: peter-evans/commit-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown** :sparkles:
          - Created by [commit-comment][1]

          [1]: https://github.com/peter-evans/commit-comment
