name: Instance image updater

# Currently, use workflow_dispatch by which we can manually run this workflow
on:
  workflow_dispatch:

jobs:
  update-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write 
#       pull-requests: write

    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: cloud-barista/cb-tumblebug
        ref: v0.6.3
        
    - name: Set credentials
      id: checker
      shell: bash
      run: |
        # Copy credentials.conf
        cp ./conf/template.credentials.conf ./conf/credentials.conf
        
        # Append AWS cred
        sed -i "s,CredentialVal01\[\$IndexAWS\]=,&${{secrets.AWS_KEY}}," ./conf/credentials.conf
        sed -i "s,CredentialVal02\[\$IndexAWS\]=,&${{secrets.AWS_VALUE}}," ./conf/credentials.conf
        cat ./conf/credentials.conf
        
        ## Dummy
        ls -al        
        GIT_STATUS=$(git status)
        
        cat > output.md <<EOF
        ### header
        - bullet
        (start)
        
        $(cat ./conf/credentials.conf)
        
        (end)
        EOF
        echo ::set-output name=output_path::"./output.md"
        
      
    - name: Create an issue from file    
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: An example issue
        content-filepath: output.md
        labels: |
          test
          need update
          good first issue
